apiVersion: v2
name: eindwerk-app
version: 1.0.0
appVersion: 1.0.0

# values.yaml
image:
repository: stefvanitterbeeck2/eindwerk-app
tag: latest
pullPolicy: IfNotPresent

service:
type: ClusterIP
port: 80
