name: Build and Release

on:
  push:
    branches: [dev, qa, main]

env:
  IMAGE_NAME: ghcr.io/stefvanitterbeeck2/eindwerk-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.stefUCLL }}
          password: ${{ secrets.123DockerHier! }}

      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update GitOps repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          tmp=$(mktemp -d)
          git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/stefvanitterbeeck2/eindwerk-cc-gitops $tmp

          BRANCH=${GITHUB_REF##*/}
          if [ "$BRANCH" = "main" ]; then ENV=prod; elif [ "$BRANCH" = "qa" ]; then ENV=qa; else ENV=dev; fi

          echo "image: ${{ env.IMAGE_NAME }}:${{ github.sha }}" > $tmp/environments/$ENV/image.txt

          cd $tmp
          git add .
          git commit -m "Update image for $ENV to ${{ github.sha }}"
          git push
